services:
  web:
    build: .
    container_name: billboard-web
    ports:
      - "8082:80"
    volumes:
      - ./html:/usr/share/nginx/html
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--quiet",
          "--tries=1",
          "--spider",
          "http://localhost:80",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
